name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        scope: '@marherb-work'

    - name: Check package.json version change
      id: check_version
      run: |
        VERSION_IN_GIT=$(git diff HEAD~ -- package.json | grep -oP '(?<="version": ")[^"]*')
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        if [ "$VERSION_IN_GIT" == "$CURRENT_VERSION" ]; then
          echo "Version has not changed."
          echo "::set-output name=version_changed::false"
        else
          echo "Version has changed."
          echo "::set-output name=version_changed::true"
        fi

    - name: Install dependencies
      if: steps.check_version.outputs.version_changed == 'true'
      run: yarn install

    - name: Build package
      if: steps.check_version.outputs.version_changed == 'true'
      run: yarn build

    - name: Publish to NPM
      if: steps.check_version.outputs.version_changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}